version: '3.7'
services:

  backend-users:
    restart: on-failure
    image: backend-users
    ports:
      - 3000:3000

  backend-videos:
    restart: on-failure
    image: backend-videos
    ports:
      - 3001:3001

  backend-playlists:
    restart: on-failure
    image: backend-playlists
    ports:
      - 3002:3002

  backend-adverts:
    restart: on-failure
    image: backend-adverts
    ports:
      - 3003:3003

  frontend:
    restart: on-failure
    image: frontend
    ports:
      - 4200:80